<% try { %>
  <%- include('main') %>
<% } catch(error) { console.log(error); %>
  <%- include('error', { error }) %>
<% } %>